"""add membership entry point

Revision ID: 2b47134fd440
Revises: 8f96765e68dd
Create Date: 2026-10-02 12:00:31.324104

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2b47134fd440"
down_revision: str | None = "8f96765e68dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "memberships",
        sa.Column(
            "entry_point",
            sa.Enum(
                "recommendation",
                "search",
                "explore",
                "notification",
                "event",
                "direct",
                name="entrypoint",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
    )
    # Autogenerate does not detect CHECK constraints on existing tables; added by hand.
    op.create_check_constraint(
        op.f("ck_memberships_entry_point_values"),
        "memberships",
        "entry_point IN ('recommendation', 'search', 'explore', 'notification', 'event', 'direct')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_memberships_entry_point_values"), "memberships", type_="check")
    op.drop_column("memberships", "entry_point")
    # ### end Alembic commands ###
