"""add group admin requests

Revision ID: 4add8072f0e9
Revises: 00b1a97f2e05
Create Date: 2026-10-10 12:58:42.102093

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4add8072f0e9"
down_revision: str | None = "00b1a97f2e05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NOTIFICATION_TYPES = (
    "'new_event', 'group_recommendation', 'group_message', 'event_reminder', 'group_review'"
)
NOTIFICATION_TYPES_WITH_ADMIN_REQUEST = f"{NOTIFICATION_TYPES}, 'admin_request'"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_admin_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                name="adminrequeststatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name=op.f("ck_group_admin_requests_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_id"],
            ["users.id"],
            name=op.f("fk_group_admin_requests_decided_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["student_groups.id"],
            name=op.f("fk_group_admin_requests_group_id_student_groups"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_group_admin_requests_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_admin_requests")),
    )
    op.create_index(
        op.f("ix_group_admin_requests_group_id"), "group_admin_requests", ["group_id"], unique=False
    )
    op.create_index(
        op.f("ix_group_admin_requests_user_id"), "group_admin_requests", ["user_id"], unique=False
    )
    op.create_index(
        "uq_group_admin_requests_one_pending",
        "group_admin_requests",
        ["group_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'pending'"),
    )
    # ### end Alembic commands ###

    # Hand-written: allow the new notification type (CHECK constraints aren't autogenerated).
    op.drop_constraint(op.f("ck_notifications_type_values"), "notifications", type_="check")
    op.create_check_constraint(
        op.f("ck_notifications_type_values"),
        "notifications",
        f"type IN ({NOTIFICATION_TYPES_WITH_ADMIN_REQUEST})",
    )
    # Groups proposed before this change got no founded year: use the year they were created.
    op.execute(
        "UPDATE student_groups SET founded_year = "
        "EXTRACT(YEAR FROM created_at AT TIME ZONE 'America/Bogota')::int "
        "WHERE founded_year IS NULL AND created_by_id IS NOT NULL"
    )


def downgrade() -> None:
    op.execute("DELETE FROM notifications WHERE type = 'admin_request'")
    op.drop_constraint(op.f("ck_notifications_type_values"), "notifications", type_="check")
    op.create_check_constraint(
        op.f("ck_notifications_type_values"), "notifications", f"type IN ({NOTIFICATION_TYPES})"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_group_admin_requests_one_pending",
        table_name="group_admin_requests",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_index(op.f("ix_group_admin_requests_user_id"), table_name="group_admin_requests")
    op.drop_index(op.f("ix_group_admin_requests_group_id"), table_name="group_admin_requests")
    op.drop_table("group_admin_requests")
    # ### end Alembic commands ###
