"""add group review status

Revision ID: b9ad7788f521
Revises: 31bfb5d6d3d9
Create Date: 2026-10-02 16:39:27.274092

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b9ad7788f521"
down_revision: str | None = "31bfb5d6d3d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NOTIFICATION_TYPES = "'new_event', 'group_recommendation', 'group_message', 'event_reminder'"
NOTIFICATION_TYPES_WITH_REVIEW = f"{NOTIFICATION_TYPES}, 'group_review'"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student_groups",
        sa.Column(
            "review_status",
            sa.Enum(
                "pending", "approved", "rejected", name="reviewstatus", native_enum=False, length=20
            ),
            server_default="approved",
            nullable=False,
        ),
    )
    op.add_column("student_groups", sa.Column("rejection_reason", sa.Text(), nullable=True))
    op.add_column(
        "student_groups", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###

    # Autogenerate does not detect CHECK constraint changes on existing tables; added by hand.
    op.create_check_constraint(
        op.f("ck_student_groups_review_status_values"),
        "student_groups",
        "review_status IN ('pending', 'approved', 'rejected')",
    )
    op.drop_constraint(op.f("ck_notifications_type_values"), "notifications", type_="check")
    op.create_check_constraint(
        op.f("ck_notifications_type_values"),
        "notifications",
        f"type IN ({NOTIFICATION_TYPES_WITH_REVIEW})",
    )


def downgrade() -> None:
    op.execute("DELETE FROM notifications WHERE type = 'group_review'")
    op.drop_constraint(op.f("ck_notifications_type_values"), "notifications", type_="check")
    op.create_check_constraint(
        op.f("ck_notifications_type_values"), "notifications", f"type IN ({NOTIFICATION_TYPES})"
    )
    op.drop_constraint(
        op.f("ck_student_groups_review_status_values"), "student_groups", type_="check"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("student_groups", "reviewed_at")
    op.drop_column("student_groups", "rejection_reason")
    op.drop_column("student_groups", "review_status")
    # ### end Alembic commands ###
