"""add releases, re-engagement cases, job and seed runs

Revision ID: 31bfb5d6d3d9
Revises: ae8c4d78acba
Create Date: 2026-10-02 12:12:30.304648

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "31bfb5d6d3d9"
down_revision: str | None = "ae8c4d78acba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job", sa.String(length=60), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_runs")),
    )
    op.create_index(op.f("ix_job_runs_job"), "job_runs", ["job"], unique=False)
    op.create_table(
        "releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("app", sa.String(length=20), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "feature_area",
            sa.Enum(
                "recommendations",
                "notifications",
                "other",
                name="featurearea",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "feature_area IN ('recommendations', 'notifications', 'other')",
            name=op.f("ck_releases_feature_area_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
        sa.UniqueConstraint("app", "version", name=op.f("uq_releases_app_version")),
    )
    op.create_table(
        "seed_runs",
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_seed_runs")),
    )
    op.create_table(
        "reengagement_cases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column(
            "arm",
            sa.Enum(
                "event_reminders",
                "group_messages",
                name="reengagementarm",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "completed", name="reengagementstatus", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evaluation_ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("weekly_attendance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("baseline_weekly_attendance", sa.Float(), nullable=False),
        sa.Column("decline_pct", sa.Float(), nullable=False),
        sa.Column("lapsed_user_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("returned_count", sa.Integer(), nullable=True),
        sa.Column("return_rate", sa.Float(), nullable=True),
        sa.Column("last_intervention_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "arm IN ('event_reminders', 'group_messages')",
            name=op.f("ck_reengagement_cases_arm_values"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'completed')", name=op.f("ck_reengagement_cases_status_values")
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["student_groups.id"],
            name=op.f("fk_reengagement_cases_group_id_student_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reengagement_cases")),
    )
    op.create_index(
        op.f("ix_reengagement_cases_group_id"), "reengagement_cases", ["group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_reengagement_cases_group_id"), table_name="reengagement_cases")
    op.drop_table("reengagement_cases")
    op.drop_table("seed_runs")
    op.drop_table("releases")
    op.drop_index(op.f("ix_job_runs_job"), table_name="job_runs")
    op.drop_table("job_runs")
    # ### end Alembic commands ###
