"""add attendance, schedules and check-in codes

Revision ID: 1bedcc9a8952
Revises: 2b47134fd440
Create Date: 2026-10-02 12:03:52.049539

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1bedcc9a8952"
down_revision: str | None = "2b47134fd440"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_blocks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=True),
        sa.Column("building_id", sa.Integer(), nullable=True),
        sa.CheckConstraint("end_time > start_time", name=op.f("ck_schedule_blocks_time_order")),
        sa.CheckConstraint(
            "weekday BETWEEN 0 AND 6", name=op.f("ck_schedule_blocks_weekday_range")
        ),
        sa.ForeignKeyConstraint(
            ["building_id"],
            ["campus_buildings.id"],
            name=op.f("fk_schedule_blocks_building_id_campus_buildings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_schedule_blocks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_blocks")),
    )
    op.create_index(
        op.f("ix_schedule_blocks_user_id"), "schedule_blocks", ["user_id"], unique=False
    )
    op.create_table(
        "event_attendance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "checked_in_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum("qr", "manual", name="checkinmethod", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("distance_m", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "method IN ('qr', 'manual')", name=op.f("ck_event_attendance_method_values")
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_event_attendance_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_event_attendance_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_attendance")),
        sa.UniqueConstraint(
            "event_id", "user_id", name=op.f("uq_event_attendance_event_id_user_id")
        ),
    )
    op.create_index(
        op.f("ix_event_attendance_event_id"), "event_attendance", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_event_attendance_user_id"), "event_attendance", ["user_id"], unique=False
    )
    # Existing events get a random code before the column becomes NOT NULL.
    op.add_column("events", sa.Column("check_in_code", sa.String(length=32), nullable=True))
    op.execute("UPDATE events SET check_in_code = substr(md5(random()::text || id::text), 1, 16)")
    op.alter_column("events", "check_in_code", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "check_in_code")
    op.drop_index(op.f("ix_event_attendance_user_id"), table_name="event_attendance")
    op.drop_index(op.f("ix_event_attendance_event_id"), table_name="event_attendance")
    op.drop_table("event_attendance")
    op.drop_index(op.f("ix_schedule_blocks_user_id"), table_name="schedule_blocks")
    op.drop_table("schedule_blocks")
    # ### end Alembic commands ###
