"""add recommendation logs and models

Revision ID: ae8c4d78acba
Revises: 96727c45e3ad
Create Date: 2026-10-02 12:09:29.208874

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ae8c4d78acba"
down_revision: str | None = "96727c45e3ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommender_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("weights", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "metrics", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommender_models")),
        sa.UniqueConstraint("version", name=op.f("uq_recommender_models_version")),
    )
    op.create_table(
        "recommendation_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("group", "event", name="recommendationkind", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "features", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("model_version", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('group', 'event')", name=op.f("ck_recommendation_logs_kind_values")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_recommendation_logs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_logs")),
    )
    op.create_index(
        "ix_recommendation_logs_kind_created_at",
        "recommendation_logs",
        ["kind", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_logs_request_id"),
        "recommendation_logs",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        "ix_recommendation_logs_user_id_item_id",
        "recommendation_logs",
        ["user_id", "item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recommendation_logs_user_id_item_id", table_name="recommendation_logs")
    op.drop_index(op.f("ix_recommendation_logs_request_id"), table_name="recommendation_logs")
    op.drop_index("ix_recommendation_logs_kind_created_at", table_name="recommendation_logs")
    op.drop_table("recommendation_logs")
    op.drop_table("recommender_models")
    # ### end Alembic commands ###
