"""add group admin invites

Revision ID: 00b1a97f2e05
Revises: b9ad7788f521
Create Date: 2026-10-09 13:31:17.156189

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00b1a97f2e05"
down_revision: str | None = "b9ad7788f521"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_admin_invites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["student_groups.id"],
            name=op.f("fk_group_admin_invites_group_id_student_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_admin_invites")),
        sa.UniqueConstraint(
            "group_id", "email", name=op.f("uq_group_admin_invites_group_id_email")
        ),
    )
    op.create_index(
        op.f("ix_group_admin_invites_email"), "group_admin_invites", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_group_admin_invites_group_id"), "group_admin_invites", ["group_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_group_admin_invites_group_id"), table_name="group_admin_invites")
    op.drop_index(op.f("ix_group_admin_invites_email"), table_name="group_admin_invites")
    op.drop_table("group_admin_invites")
    # ### end Alembic commands ###
